### ISSUE TITLE
Minor errors in the readme and possible improvements

### ISSUE THREAD

**Issue by Vincent-Stragier** [SuperHouse/ESPF#1]
Hello,

There is an error in the spelling of the chip name.

``CP2012N USB-to-serial converter`` instead of ``CP2102N USB-to-serial converter.``
And last line ``capy`` instead of ``copy``

Also the link to https://www.superhouse.tv/espf is leading to nothing.

I did not go in depth in your project but maybe you should consider to change the voltage regulator for an [AMS-1117 3.3V](http://www.advanced-monolithic.com/pdf/ds1117.pdf) (I think it's adviced in the ESP32 datasheet to use a 3.3V voltage regulator that can deliver 1A or more).

Also a zip with the gerber files as a release could be a plus (I don't know with EDA you did use) as well as the BOM list to replicate the project.

You have a very nice project ;-)

Have a nice day,

Vincent

**Comment by jonoxer** [comment]
Thanks for your help, Vincent! I didn't notice those mistakes. I'll fix them now.

I use the AMS1117 in many of my other projects, but it's an old chip with poor specs compared to newer ones like the AP2112. The AP2112 is *much* better than the AMS1117 in every single spec except for peak current rating, and it's about 1/8th the size. In fact the voltage overhead of the AMS1117 means that it's operating only 0.55V away from the limits of its spec when supplying 3.3V from a 5V power source, which is a small margin for error.

I've used the AP2112 on many ESPxx projects and never had a problem with the peak current rating.

The design files can be opened in either EAGLE or Fusion 360, which can be used to generate production files to suit the design rules for the factory that will make the boards, including the bill of materials. I don't find that generic Gerber files are much use and I always generate them to suit the factory, so I don't bother including them with my projects. Anyone who wants to fabricate the boards will probably need to generate their own Gerbers anyway.

The URL is broken because I haven't released this project yet. It's still a draft, and I need to make the page for it.

Cheers :-)

Jon
